name: "Supernova Sync"
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    paths:
      - "token_values/**"

jobs:
  sync_reference_tokens:
    name: Sync Reference tokens
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'sync reference')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.ADMIN_TOKEN}}
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            token_values/**/reference.json

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Update Reference Tokens
        id: tokens_data
        uses: ./.github/workflows/get_tokens_data
        with:
          changes: ${{ steps.changed-files.outputs.all_changed_files }}
      - run: echo "references changed ${{ steps.tokens_data.outputs.updates }}"
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: "sync reference"
  sync_with_supernova:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'sync reference')"
    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the CLI utility can read it
      - uses: actions/checkout@v3

      # Setup node to use with CLI. 14+ is required
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      # Install Supernova CLI
      - name: Install Supernova CLI dependency
        run: npm install --g @supernovaio/cli

      # Sync tokens
      - name: Synchronize tokens with Supernova
        run: supernova sync-tokens --apiKey=${{ secrets.SUPERNOVA_AUTH_TOKEN}} --designSystemId=7721 --tokenFilePath="token_values/product/" --configFilePath="token_values/product/supernova.settings.json"
