name: "Supernova Sync"
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    paths:
      - "token_values/**"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Sync Figma Tokens and Supernova
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            token_values/**/reference.json

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Update Reference Tokens
        id: tokens_data
        uses: ./.github/workflows/get_tokens_data
        with:
          changes: ${{ steps.changed-files.outputs.all_changed_files }}
      - run: echo "references changed ${{ steps.tokens_data.outputs.updates }}"
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_email: pablo.romero-jaren@electrolux.com
          author_name: pabloromeroelux
          committer_email: pablo.romero-jaren@electrolux.com
          committer_name: pabloromeroelux
