on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job to do stuff
    steps:
      - name: Action test
        id: test
        uses: pabloromeroelux/pabloactiontest@v1.0.1 # Uses an action in the root directory
        with:
          key: $SUPERNOVA_AUTH_TOKEN
          # Use the output from the `hello` step
      - name: Get the output milliseconds
        run: echo "Key received? ${{ steps.test.outputs.response }}"
