on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job to do stuff
    steps:
      - name: Action test
        id: supernova_sync
        uses: pabloromeroelux/pabloactiontest@v1.0.2patch5
        with:
          key: "abcdef"
      - name: Comfirm it worked
        run: echo "Key received? ${{ steps.supernova_sync.outputs.response }}"
