on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Sync Figma Tokens and Supernova
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Tokens Data
        id: tokens_data
        uses: ./.github/workflows/get_tokens_data
      - name: Log
        run: echo "data ${{ steps.tokens_data.outputs.data }}"
      - name: Commit
      - uses: EndBug/add-and-commit@v9
        add: "--all"
        commit: "-m 'unify reference tokens'"
      - name: Map tokens to Supernova
        id: supernova_sync
        uses: pabloromeroelux/figma_supernova_tokens_sync_action@main
        with:
          key: ${{ secrets.SUPERNOVA_AUTH_TOKEN }}
          dsid: "7721"
          vid: "7884"
          tokens: ${{ steps.tokens_data.outputs.data }}
      - name: Comfirmation
        run: echo "Key received? ${{ steps.supernova_sync.outputs.response }}"
