on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Sync Figma Tokens and Supernova
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Tokens Data
        id: tokens_data
        uses: ./.github/workflows/get_tokens_data
      - name: Map tokens to Supernova
        id: supernova_sync
        uses: pabloromeroelux/pabloactiontest@v1.0.2main
        with:
          key: ${{ secrets.SUPERNOVA_AUTH_TOKEN }}
          dsid: "7721"
          vid: "7884"
      - name: Comfirmation
        run: echo "Key received? ${{ steps.supernova_sync.outputs.response }}"
