on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job to do stuff
    steps:
      - name: Action test
        id: supernova_sync
        uses: pabloromeroelux/pabloactiontest@v1.0.2patch7
        with:
          key: ${{ secrets.SUPERNOVA_AUTH_TOKEN }}
          dsid: "7721"
          vid: "7884"
      - name: Comfirm it worked
        run: echo "Key received? ${{ steps.supernova_sync.outputs.response }}"
