on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job to do stuff
    steps:
      - name: Action test
        id: supernova_sync
        uses: pabloromeroelux/pabloactiontest@v1.0.2patch3 # Uses an action in the root directory
        with:
          key: $SUPERNOVA_AUTH_TOKEN
          # Use the output from the `hello` step
      - name: Comfirm it worked
        run: echo "Key received? ${{ steps.supernova_sync.outputs.response }}"
