on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job to do stuff
    steps:
      - name: Action test
        uses: pabloromeroelux/pabloactiontest@v1.0.0 # Uses an action in the root directory
        with:
          milliseconds: 200
